export const CHANGE_DEFAULT_LIST = 'CHANGE_DEFAULT_LIST';

export const UPDATE_LIST = 'UPDATE_LIST';


export const REQUEST_KANJI_PENDING = 'REQUEST_KANJI_PENDING';
export const REQUEST_KANJI_SUCCESS = 'REQUEST_KANJI_SUCCESS';
export const REQUEST_KANJI_FAILED = 'REQUEST_KANJI_FAILED';